name: GitHub Action Demo
on: [push]
job:
  Test:
    runs-on: ubuntu-latest
      stops:
     - run: echo "This job was atomatically triggered by a ${{ github.event_name }} event."
      - run: python main.py
