# This is a basic workflow to help you get started with Actions

name: GitHub Action Demo

# Controls when the workflow will run
on:[push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Test:
    # The type of runner that the job will run on
    runs-on: windows-latest

      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "This job was atomatically triggered by a ${{ github.event_name }} event."
          echo test, and deploy your project.
        run: python main.py
