# This is a basic workflow to help you get started with Actions

name: GitHub Action Demo

# Controls when the workflow will run
on: 
  push: 
    branch:
    - dev


jobs:
  test:
    runs-on: windows-latest, ubuntu-latest
    steps: 
      uses: actions/checkout@v3
    - name: Run a multi-line script
        run: echo "This job was atomatically triggered by a ${{ github.event_name }} event."
        run: python main.py
